# Importing Data Using Pandas - Lab

## Introduction

In this lab, you'll get some practice with loading files with summary or metadata, and if you find that easy, the optional "level up" content covers loading data from a currupted csv file!

## Objectives
You will be able to:
* Import data from csv files and Excel files
* Understand and explain key arguments for imports
* Save information to csv and Excel files
* Access data within a Pandas DataFrame (print() and .head())

#  Loading Files with Summary or Meta Data

Load either of the files Zipcode_Demos.csv or Zipcode_Demos.xlsx. What's going on with this dataset? Clean it up into a useable format and describe the nuances of how the data is currently formatted.

All data files are stored in a folder titled 'Data'.

In [4]:
import pandas as pd
import numpy as np
df = pd.read_csv("Data/Zipcode_Demos.csv")
df.tail(-6)

,0,Average Statistics,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46
6,7,PERCENT MALE,0.396,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,COUNT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,9,PERCENT GENDER UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,10,COUNT GENDER TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,11,PERCENT GENDER TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,12,COUNT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,13,PERCENT PACIFIC ISLANDER,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,14,COUNT HISPANIC LATINO,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,15,PERCENT HISPANIC LATINO,0.105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,16,COUNT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,17,PERCENT AMERICAN INDIAN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,18,COUNT ASIAN NON HISPANIC,3.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,19,PERCENT ASIAN NON HISPANIC,0.437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,20,COUNT WHITE NON HISPANIC,0.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,21,PERCENT WHITE NON HISPANIC,0.036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,COUNT BLACK NON HISPANIC,2.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,23,PERCENT BLACK NON HISPANIC,0.181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,24,COUNT OTHER ETHNICITY,0.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,25,PERCENT OTHER ETHNICITY,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,26,COUNT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,27,PERCENT ETHNICITY UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,28,COUNT ETHNICITY TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,29,PERCENT ETHNICITY TOTAL,79.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,30,COUNT PERMANENT RESIDENT ALIEN,0.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,31,PERCENT PERMANENT RESIDENT ALIEN,0.061,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,32,COUNT US CITIZEN,8.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,PERCENT US CITIZEN,0.739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,34,COUNT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,PERCENT OTHER CITIZEN STATUS,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,36,COUNT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,37,PERCENT CITIZEN STATUS UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,38,COUNT CITIZEN STATUS TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,PERCENT CITIZEN STATUS TOTAL,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,COUNT RECEIVES PUBLIC ASSISTANCE,2.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,41,PERCENT RECEIVES PUBLIC ASSISTANCE,0.151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,42,COUNT NRECEIVES PUBLIC ASSISTANCE,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,PERCENT NRECEIVES PUBLIC ASSISTANCE,0.649,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,44,COUNT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,45,PERCENT PUBLIC ASSISTANCE UNKNOWN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,46,COUNT PUBLIC ASSISTANCE TOTAL,9.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,47,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,48,10001,44,22,0.5,22,0.5,0,0,44,...,44,100,20,0.45,24,0.55,0,0,44,100
48,49,10002,35,19,0.54,16,0.46,0,0,35,...,35,100,2,0.06,33,0.94,0,0,35,100
49,50,10003,1,1,1,0,0,0,0,1,...,1,100,0,0,1,1,0,0,1,100
50,51,10004,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,52,10005,2,2,1,0,0,0,0,2,...,2,100,0,0,2,1,0,0,2,100
52,53,10006,6,2,0.33,4,0.67,0,0,6,...,6,100,0,0,6,1,0,0,6,100
53,54,10007,1,0,0,1,1,0,0,1,...,1,100,1,1,0,0,0,0,1,100
54,55,10009,2,0,0,2,1,0,0,2,...,2,100,0,0,2,1,0,0,2,100
55,56,10010,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,57,10011,3,2,0.67,1,0.33,0,0,3,...,3,100,0,0,3,1,0,0,3,100

In [3]:
col_names = np.array(df.iloc[46,:])[1:]

good_entries = df.iloc[-10:,1:]
good_entries.columns = col_names
display(good_entries)

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN,COUNT PUBLIC ASSISTANCE TOTAL,PERCENT PUBLIC ASSISTANCE TOTAL
47,10001,44,22,0.5,22,0.5,0,0,44,100,...,44,100,20,0.45,24,0.55,0,0,44,100
48,10002,35,19,0.54,16,0.46,0,0,35,100,...,35,100,2,0.06,33,0.94,0,0,35,100
49,10003,1,1,1,0,0,0,0,1,100,...,1,100,0,0,1,1,0,0,1,100
50,10004,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
51,10005,2,2,1,0,0,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
52,10006,6,2,0.33,4,0.67,0,0,6,100,...,6,100,0,0,6,1,0,0,6,100
53,10007,1,0,0,1,1,0,0,1,100,...,1,100,1,1,0,0,0,0,1,100
54,10009,2,0,0,2,1,0,0,2,100,...,2,100,0,0,2,1,0,0,2,100
55,10010,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
56,10011,3,2,0.67,1,0.33,0,0,3,100,...,3,100,0,0,3,1,0,0,3,100

In [4]:
avg_of_entries = df.iloc[1:45,1:3].T
avg_of_entries.columns = np.array(avg_of_entries.loc['Average Statistics'])[:]
avg_of_entries = avg_of_entries[-1:]
avg_of_entries

,JURISDICTION NAME,COUNT PARTICIPANTS,COUNT FEMALE,PERCENT FEMALE,COUNT MALE,PERCENT MALE,COUNT GENDER UNKNOWN,PERCENT GENDER UNKNOWN,COUNT GENDER TOTAL,PERCENT GENDER TOTAL,...,COUNT CITIZEN STATUS UNKNOWN,PERCENT CITIZEN STATUS UNKNOWN,COUNT CITIZEN STATUS TOTAL,PERCENT CITIZEN STATUS TOTAL,COUNT RECEIVES PUBLIC ASSISTANCE,PERCENT RECEIVES PUBLIC ASSISTANCE,COUNT NRECEIVES PUBLIC ASSISTANCE,PERCENT NRECEIVES PUBLIC ASSISTANCE,COUNT PUBLIC ASSISTANCE UNKNOWN,PERCENT PUBLIC ASSISTANCE UNKNOWN
Unnamed: 2,10005.8,9.4,4.8,0.404,4.6,0.396,0,0,9.4,80,...,0,0,9.4,80,2.3,0.151,7.1,0.649,0,0

In [5]:
col_names = np.array(df.iloc[46,:])[1:]

## Level Up (Optional)

### Loading Corrupt CSV files

Occassionally, you encountered some really ill formatted data. One example of this can be data that has strings containing commas in a csv file. Under the standard protocol, when this occurs, one is suppossed to use quotes to differentiate between the commas denoting fields and commas within those fields themselves. For example, we could have a table like this:  

ReviewerID,Rating,N_reviews,Review,VenueID
123456,4,137,This restuarant was pretty good, we had a great time.,98765

Which should be saved like this if it were a csv (to avoid confusion with the commas in the Review text):
"ReviewerID","Rating","N_reviews","Review","VenueID"
"123456","4","137","This restuarant was pretty good, we had a great time.","98765"

Attempt to import the corrupt file, or at least a small preview of it. It is appropriately titled Yelp_Reviews_corrupt.csv. Investigate some of the intricacies of skipping rows to then pass over this error and comment on what you think is going on.

In [22]:
#Hint: here's a useful programming pattern to use.
file = 'Data/Yelp_Reviews_Corrupt.csv'
fail_rows = []
for i in range(1,5000):
    try:
        #print(i)
        #pd.read_csv()
        df2 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows = i, skiprows = [1961, 1962])
    except Exception as e:
        print(e, i)
        fail_rows.append(i)
        print(f'row # {i} failed, saved to fail_rows')
        break
        #print(e)
        #handle your exception e

Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11
 1961
row # 1961 failed, saved to fail_rows

In [54]:
fail_rows

[340, 1961, 1962, 1961, 1961, 1950]

In [58]:
cleaned_1 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows = 339)
display(cleaned_1)

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0.0,dDl8zu1vWPdKGihJrwQbpw,5.0,I love this place! My fiance And I go here atl...,0.0,msQe1u7Z_XuqjGoqhB0J5g
1,2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1.0,LZp4UX5zK3e-c5ZGSeo3kA,1.0,Terrible. Dry corn bread. Rib tips were all fa...,3.0,msQe1u7Z_XuqjGoqhB0J5g
2,4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0.0,jsDu6QEJHbwP2Blom1PLCA,5.0,Delicious healthy food. The steak is amazing. ...,0.0,msQe1u7Z_XuqjGoqhB0J5g
3,5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0.0,pfavA0hr3nyqO61oupj-lA,1.0,This place sucks. The customer service is horr...,2.0,msQe1u7Z_XuqjGoqhB0J5g
4,10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0.0,STiFMww2z31siPY7BWNC2g,5.0,I have been an Emerald Club member for a numbe...,0.0,TlvV-xJhmh7LCwJYXkV-cg
5,11,UBv8heCQR0RPnUQG0zkXIQ,0,2016-09-23,0.0,HkYqGb0Gplmmk-xlHTRBoA,1.0,The score should be negative. Its HORRIBLE. Th...,0.0,NhOc64RsrTT1Dls50yYW8g
6,12,hdgYnadxg0GANhWOJabr2g,0,2014-08-23,0.0,RgqWdZA4xR023iP3T6jVfA,5.0,I went there twice and I am pretty happy with ...,0.0,NhOc64RsrTT1Dls50yYW8g
7,19,gZGsReG0VeX4uKViHTB9EQ,0,2017-08-16,0.0,51RHs_V_fjuistnuKxNpEg,5.0,Finally! After trying many Mexican restaurants...,0.0,5ngpW5tf3ep680eG1HxHzA
8,25,f-v1fvtnbdw_QQRsCnwH-g,0,2017-11-18,0.0,alI_kRKyEHfdHibYGgtJbw,1.0,I have to write a review on the Fractured Prun...,0.0,Fc_nb6N6Sdurqb-rwsY1Bw
9,26,yz66FIUPDKGhILDWzRLeKg,0,2017-11-18,0.0,85DRIjwPJOTb4q0qOlBstw,1.0,I wish i could tell you all about the food but...,1.0,Fc_nb6N6Sdurqb-rwsY1Bw
10,27,6qDRqHWqf0EeHupSUEBfKg,0,2015-12-10,0.0,GbiLIKmQPVCBtdNkTVdVSA,5.0,Wonderful! One of my favorite places. BBQ is e...,0.0,G22ITfVETYHtIhnn5lLRrQ
11,28,7AlULGZI1pHt0imODsqdkg,0,2012-02-12,0.0,UaHgsL0xS4UnJ_iKqeOk_w,5.0,The price is about the same as Quizinos. The s...,0.0,FjH3TH8OvHGLNEbzdEYlNg
12,29,th4pZ5LkoIIkb1Vmu_m2DA,0,2012-02-12,0.0,c4zzAD1S6721Fh-acCBy-g,4.0,The food was ok. You get a lot of food for the...,0.0,FjH3TH8OvHGLNEbzdEYlNg
13,30,nsSfCKW9KDB4COj9bzXApw,0,2012-02-12,0.0,TTBwocu2mvqJFJrwmJN0Sw,5.0,The staff were friendly and helpful. The food ...,1.0,FjH3TH8OvHGLNEbzdEYlNg
14,31,cP8ErpZfRzdVR5Fvks-pnQ,0,2012-02-12,0.0,-CresnnXQSHrQ85Ogm-Pqw,5.0,The staff were very helpful. We painted potter...,0.0,FjH3TH8OvHGLNEbzdEYlNg
15,32,Edr6SafmQrZa6CcFuItoqg,0,2014-06-03,0.0,U04YgYr4PiGUxB46J4xapg,2.0,Limited vegetarian options. Ordered Greek sala...,0.0,B7Fh30KQT1xPSGt_pIhRRA
16,35,SpJYus_184M2TdT7t52rIA,0,2016-11-18,0.0,s9cpVj40VR_yl0lXbZQe6w,5.0,I trust my vehicles here. Comparable prices. M...,0.0,zx_Op2OAOM_fRic9tU-jqA
17,40,qdC2h3MqCNussc5lhzL7gg,0,2015-11-05,0.0,AJ0IglpYAp2D0daOlVGIdg,1.0,This place doesn't even deserve 1 star. Horrib...,18.0,Ka7TIp74VHSa90rfdg4_2g
18,41,XgRDG9E_WLEbl8S-QUqQkQ,0,2015-11-05,0.0,5D_MsAJHrMa8QKkpE3g1Sg,5.0,The butter burger was cooked perfectly and jui...,0.0,Ka7TIp74VHSa90rfdg4_2g
19,42,awgoBwuhzlLGKEIverTGjQ,0,2017-01-21,0.0,5bWN_IN8MQGjJ6_ZIXffDw,5.0,Best location ever! I love love love the manag...,0.0,yyPHK6khPa4-ErV9U32x3A
20,74,iO3GuIiZxzv-iETGVnoeVA,0,2016-11-06,0.0,RW_mYzHYfdqn6g7xVgIcKg,4.0,This was a real fun time. Lots of laughs and e...,NaN,NaN
21,Food was pretty decent as well. Like the salad...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,4 stars since I'm bummed there were no mojitos.,0,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,79,yz3KtngrF2PQrif8JW7gdw,0,2016-05-28,0.0,SLA1YP9doUc8h-6Kd34QmA,1.0,Horrible. The smart ones have closed their acc...,NaN,NaN
24,Manager doesn't take accountability for the la...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Be smart take you money out and run.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,83,T2XdzAcj0M_kBD9_BHfZlw,0,2016-05-08,0.0,qxPiEGIHy5xyVy78avH5Rg,4.0,Love the 'old school' ambiance. Friendly staff...,NaN,NaN
27,Come for the popcorn and drinks.,1,0pf5VuzE4_1pwj5NJHG5TQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,92,AtbXj3Rg1GF6Dj5zu6KCDg,0,2012-10-11,0.0,q6ij-nz5d_hvdjuelho1pQ,5.0,Better service and much better prices than the...,0.0,WnM2AmNIint5b5f688nmPg
29,95,6tSvz_21BMo3a4GaItwa0g,0,2017-04-08,0.0,66FSK2J1uHJqVI1Z8QiFGw,4.0,I love how they have no rice sushi options. Th...,0.0,Yy_iGXxLpL6tYDQoE-6XVg
...,...,...,...,...,...,...,...,...,...,...
309,What a joke where do they find these people? N...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
310,Tip - save your money for a Timmy's or other c...,1,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311,593,c35qzLN6ItDpVIoj2uQW4Q,0,2016-01-13,0.0,N6uYKO8sow0QoBKpcJZNGQ,5.0,I really love the butternut squash soup here.....,NaN,NaN
312,Curry Lamb Wrap - Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
313,Has a great spicy kick .... Perfect for winter...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
314,Chicken Wrap- Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
315,Chicken is tender and cooked simple but well. ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
316,Steak Wrap- Usually great but last time was wa...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
317,The fact that it was over cooked made me think...,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
318,596,p4GDM1mu0doucp1xDlKdrw,0,2016-03-03,0.0,KYQPmCwO0DPXS-EDb7NBBA,1.0,Suffocation best describes the services given ...,NaN,NaN
319,I will be going to the other locations from no...,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
320,597,LB7r3hZmb4NXb2jDQmmQ9w,0,2015-01-12,0.0,cyPaZNZ77Kc2nZas20FqsA,4.0,Food is good. Fresh house made broth great fla...,0.0,kBNFdviedCPFWyR-wVaAzw
321,598,5N8R7ALESZ30EoAzVJtabw,0,2015-06-30,0.0,EVd_tGYKSAI0yyHodvzUxw,5.0,Pricy but really good waffles,NaN,NaN
322,Good chicken portion. Let's keep it like that ...,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,600,k7D1eFxN-_Ry491C-RiMpw,0,2016-01-13,0.0,kCieN9PVbrZe40eNYDZM9Q,1.0,Terrible service .... Terrible over cooked win...,NaN,NaN
324,Literally was like eating dried out oil jerky ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
325,Tip* save your time and money go somewhere els...,1,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,601,gEv1Og5uGDLw9HkbKSGUZw,0,2016-02-27,0.0,AVutsGbOCKlesul0HrXSFg,5.0,Love love love this place!,NaN,NaN
327,Tacos tacos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
328,Firstly just need to say I put the habanero ho...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
329,Shrimp tacos were juicy and great,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
330,Fish taco was great and flaky,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331,They had a Trout taco day feature which was gr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
332,Chicken and beef tacos had a decent amount of ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
333,The Vegetarian option was surprisingly also ve...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
334,Ceviche love the jalapeño touch inside but fis...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
335,Margarita pitcher could use a little more lime...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,Over all very great vibes...music is beautiful...,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,603,b4LmLgVdbhM-nc1IZc5Weg,0,2015-03-26,0.0,m-xTYOTdkk5dOf4JLnbLVA,5.0,Love love love ! Great food! Really hits the t...,NaN,NaN
338,have been here many a times .... Love how they...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
cleaned_2 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows = 1960, skiprows = [340])
display(cleaned_2[335:345])

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
335,Margarita pitcher could use a little more lime...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
336,Over all very great vibes...music is beautiful...,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,603,b4LmLgVdbhM-nc1IZc5Weg,0,2015-03-26,0.0,m-xTYOTdkk5dOf4JLnbLVA,5.0,Love love love ! Great food! Really hits the t...,NaN,NaN
338,have been here many a times .... Love how they...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
339,(Summer nights)Lobster Bisque - creamy buttery...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
340,(Summer nights)Scorpion Fish with Roasted Garl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,(AIl year)personally love the smaller oysters ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,(Entering spring)Tuna Tartar -Fresh And Toasts...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
343,(Autumn) Seared Tuna with a creamy broth was a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
344,Clam Chowder - Creamy perfection with a little...,0,kBNFdviedCPFWyR-wVaAzw,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
#fail_rows.append(340)
fail_rows = [340, 1961]

In [52]:
print(fail_rows, ': known rows that fail')
for i in range(1950, 5000):
    try:
        #print(i)
        #pd.read_csv()
        df3 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', nrows = i, skiprows = 1961)
    except Exception as e:
        print(e, i)
        fail_rows.append(i)
        print(f'row # {i} failed, saved to fail_rows')
        break
        #print(e)
        #handle your exception e
fail_rows

[340, 1961, 1962, 1961, 1961] : known rows that fail
Error tokenizing data. C error: Expected 10 fields in line 2331, saw 11
 1950
row # 1950 failed, saved to fail_rows

[340, 1961, 1962, 1961, 1961, 1950]

In [53]:
# cleaned_2 = pd.read_csv('Data/Yelp_Reviews_Corrupt.csv', skiprows = fail_rows)
# cleaned_2